BBPredict.cpp
float getBbWidth(float *bb)
Returns width of Boundingbox. bb Boundingbox
Referenced by predictbb.
float getBbHeight(float *bb)
Returns hight of Boundingbox. bb Boundingbox
Referenced by predictbb.
int predictbb(float *bb0, CvPoint2D32f *pt0, CvPoint2D32f *pt1, int nPts, float *bb1, float *shift)
Calculates the new (moved and resized) Bounding box. Calculation based on all relative distance changes of all points to every point. Then the Median of the relative Values is used.
References getBbHeight, getBbWidth, getMedianUnmanaged.
Referenced by fbtrack.