ComponentLabeling.cpp
const CvPoint freemanCodeIncrement[8][8]
Conversion from freeman code to coordinate increments (counterclockwise).
unsigned char GET_ABOVE_IMAGEPIXEL(unsigned char *currentPixel, IplImage *image)
FUNCIÓ:FUNCIONALITAT:PARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/29MODIFICACIÓ: Data. Autor. Descripció.
unsigned char GET_BELOW_IMAGEPIXEL(unsigned char *currentPixel, IplImage *image)
unsigned char GET_IMAGE_PIXEL(IplImage *image, CvPoint p)
Referenced by tracer.
bool GET_IMAGEMASK_PIXEL(IplImage *mask, CvPoint p)
References NULL.
Referenced by tracer.
bool GET_BELOW_VISITEDPIXEL(bool *currentPixel, int imageWidth)
Referenced by ComponentLabeling.
void ASSIGN_LABEL(CvPoint p, t_labelType *labels, int imageWidth, int newLabel)
FUNCIÓ: ASSIGN_LABELFUNCIONALITAT: Assigns label value to label imagePARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/29MODIFICACIÓ: Data. Autor. Descripció.
Referenced by contourTracing.
void ASSIGN_VISITED(CvPoint p, bool *visitedPoints, int imageWidth)
Referenced by tracer.
bool ComponentLabeling(IplImage *inputImage, IplImage *maskImage, unsigned char backgroundColor, Blob_vector &blobs)
FUNCIÓ: ComponentLabelingFUNCIONALITAT: Calcula els components binaris (blobs) d'una imatge amb connectivitat a 8PARÀMETRES: inputImage: image to segment (pixel values different than blobColor are treated as background)maskImage: if not NULL, all the pixels equal to 0 in mask are skipped in input imagebackgroundColor: color of background (ignored pixels)blobs: blob vector destination RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/21MODIFICACIÓ: Data. Autor. Descripció.NOTA: Algorithm based on "A linear-time component labeling algorithm using contour tracing technique", F.Chang et al
References CBlob::AddInternalContour, contourTracing, GET_BELOW_VISITEDPIXEL, CBlob::GetExternalContour, CBlob::GetStorage.
void contourTracing(IplImage *image, IplImage *maskImage, CvPoint contourStart, t_labelType *labels, bool *visitedPoints, t_labelType label, bool internalContour, unsigned char backgroundColor, CBlobContour *currentBlobcontour)
FUNCIÓ:FUNCIONALITAT:PARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/29MODIFICACIÓ: Data. Autor. Descripció.
References CBlobContour::AddChainCode, ASSIGN_LABEL, tracer.
Referenced by ComponentLabeling.
CvPoint tracer(IplImage *image, IplImage *maskImage, CvPoint P, bool *visitedPoints, short initialMovement, unsigned char backgroundColor, short &movement)
FUNCIÓ: tracerFUNCIONALITAT: Searches for next point of a contourPARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/30MODIFICACIÓ: Data. Autor. Descripció.
References ASSIGN_VISITED, GET_IMAGE_PIXEL, GET_IMAGEMASK_PIXEL.
Referenced by contourTracing.