ImAcq.cpp
ImAcq* imAcqAlloc()
References ImAcq::camNo, ImAcq::currentFrame, ImAcq::fps, ImAcq::lastFrame, ImAcq::method.
Referenced by main.
void imAcqInit(ImAcq *imAcq)
References ImAcq::camNo, ImAcq::capture, ImAcq::currentFrame, IMACQ_CAM, IMACQ_STREAM, IMACQ_VID, imAcqVidGetNumberOfFrames, ImAcq::imgPath, ImAcq::lastFrame, ImAcq::method, NULL, ImAcq::startFrame, ImAcq::startTime.
Referenced by main.
void imAcqFree(ImAcq *imAcq)
References ImAcq::capture, IMACQ_CAM, IMACQ_STREAM, IMACQ_VID, ImAcq::method.
Referenced by Main::~Main.
IplImage* imAcqLoadFrame(ImAcq *imAcq, int fNo)
References ImAcq::imgPath.
Referenced by imAcqGetImgByCurrentTime, imAcqLoadCurrentFrame.
IplImage* imAcqLoadCurrentFrame(ImAcq *imAcq)
References ImAcq::currentFrame, imAcqLoadFrame.
Referenced by imAcqGetImg.
IplImage* imAcqGetImgByCurrentTime(ImAcq *imAcq)
References ImAcq::capture, ImAcq::fps, IMACQ_CAM, IMACQ_STREAM, imAcqGrab, imAcqLoadFrame, ImAcq::lastFrame, ImAcq::method, ImAcq::startFrame, ImAcq::startTime.
Referenced by imAcqGetImg.
IplImage* imAcqGetImg(ImAcq *imAcq)
References ImAcq::capture, IMACQ_CAM, IMACQ_IMGS, IMACQ_LIVESIM, IMACQ_STREAM, IMACQ_VID, imAcqAdvance, imAcqGetImgByCurrentTime, imAcqGrab, imAcqLoadCurrentFrame, ImAcq::method.
Referenced by Main::doWork.
IplImage* imAcqGrab(CvCapture *capture)
References NULL.
Referenced by imAcqGetImg, imAcqGetImgByCurrentTime.
void imAcqAdvance(ImAcq *imAcq)
References ImAcq::currentFrame.
Referenced by imAcqGetImg.
int imAcqHasMoreFrames(ImAcq *imAcq)
References ImAcq::currentFrame, ImAcq::lastFrame.
Referenced by Main::doWork.
int imAcqVidGetNumberOfFrames(ImAcq *imAcq)
References ImAcq::capture.
Referenced by imAcqInit.