Lk.cpp
const int MAX_COUNT
const int MAX_IMG
Referenced by initImgs.
const double N_A_N
Referenced by trackLK.
int win_size_lk
Size of the search window of each pyramid level in cvCalcOpticalFlowPyrLK.
Referenced by trackLK.
CvPoint2D32f* points[3][3]
Referenced by trackLK.
IplImage** PYR
void euclideanDistance(CvPoint2D32f *point1, CvPoint2D32f *point2, float *match, int nPts)
Calculates euclidean distance between the point pairs. point1 Array of points. Pairs with point2 at every Position. point2 Array of points. Pairs with point1 at every Position. match Output: Contains the result of the distance calculation. Must have the length of nPts. nPts Number of pairs.
Referenced by trackLK.
void normCrossCorrelation(IplImage *imgI, IplImage *imgJ, CvPoint2D32f *points0, CvPoint2D32f *points1, int nPts, char *status, float *match, int winsize, int method)
Calculates normalized cross correlation for every point. imgI Image 1. imgJ Image 2. points0 Array of points of imgI points1 Array of points of imgJ nPts Length of array/number of points. status Switch which point pairs should be calculated. if status[i] == 1 => match[i] is calculated. else match[i] = 0.0 match Output: Array will contain ncc values. 0.0 if not calculated. winsize Size of quadratic area around the point which is compared. method Specifies the way how image regions are compared. see cvMatchTemplate
Referenced by trackLK.
void initImgs()
Needed before start of trackLK and at the end of the program for cleanup. Handles PYR(Pyramid cache) variable.
References MAX_IMG.
Referenced by fbtrack.
int trackLK(IplImage *imgI, IplImage *imgJ, float ptsI[], int nPtsI, float ptsJ[], int nPtsJ, int level, float *fb, float *ncc, char *status)
Tracks Points from 1.Image to 2.Image. Need initImgs before start and at the end of the program for cleanup. imgI previous Image source. (isn't changed) imgJ actual Image target. (isn't changed) ptsI points to track from first Image. Format [0] = x1, [1] = y1, [2] = x2 ... nPtsI number of Points to track from first Image ptsJ container for calculated points of second Image. Must have the length of nPtsI. nPtsJ number of Points level Pyramidlevel, default 5 fb forward-backward confidence value. (corresponds to euclidean distance between). Must have the length of nPtsI: nPtsI * sizeof(float). ncc normCrossCorrelation values. needs as inputlength nPtsI * sizeof(float) status Indicates positive tracks. 1 = PosTrack 0 = NegTrack needs as inputlength nPtsI * sizeof(char) Based Matlab function: lk(2,imgI,imgJ,ptsI,ptsJ,Level) (Level is optional)
References euclideanDistance, N_A_N, normCrossCorrelation, points, win_size_lk.
Referenced by fbtrack.