Median.h
float getMedian(float arr[], int n)
Returns median of the array. Changes array! arr the array n length of array Calculates Median of the array. Don't change array(makes copy). arr the array n length of array
References getMedianUnmanaged.
Referenced by fbtrack.
float getMedianUnmanaged(float arr[], int n)
Calculates Median of the array. Don't change array(makes copy). arr the array n length of array Returns median of the array. Changes array! arr the array n length of array This Quickselect routine is based on the algorithm described in "Numerical recipes in C", Second Edition, Cambridge University Press, 1992, Section 8.5, ISBN 0-521-43108-5 This code by Nicolas Devillard - 1998. Public domain.
References ELEM_SWAP.
Referenced by getMedian, predictbb.