tld::DetectionResult
bool tld::DetectionResult::containsValidData
Referenced by DetectionResult, release, reset.
std::vector<cv::Rect>* tld::DetectionResult::fgList
Referenced by DetectionResult, Main::doWork, release, reset.
float* tld::DetectionResult::posteriors
Referenced by tld::EnsembleClassifier::classifyWindow, DetectionResult, tld::EnsembleClassifier::filter, init, release.
std::vector<int>* tld::DetectionResult::confidentIndices
Referenced by tld::Clustering::clusterConfidentIndices, DetectionResult, init, release, reset.
int* tld::DetectionResult::featureVectors
Referenced by tld::EnsembleClassifier::classifyWindow, DetectionResult, init, release.
float* tld::DetectionResult::variances
Referenced by DetectionResult, tld::VarianceFilter::filter, init, release.
int tld::DetectionResult::numClusters
Referenced by tld::Clustering::clusterConfidentIndices, DetectionResult, reset.
cv::Rect* tld::DetectionResult::detectorBB
Referenced by DetectionResult, release, reset.
tld::DetectionResult::DetectionResult()
References confidentIndices, containsValidData, detectorBB, featureVectors, fgList, numClusters, posteriors, variances.
tld::DetectionResult::~DetectionResult()
References release.
void tld::DetectionResult::init(int numWindows, int numTrees)
References confidentIndices, featureVectors, posteriors, variances.
Referenced by tld::DetectorCascade::propagateMembers.
void tld::DetectionResult::reset()
References confidentIndices, containsValidData, detectorBB, fgList, NULL, numClusters.
Referenced by tld::DetectorCascade::cleanPreviousData.
void tld::DetectionResult::release()
References confidentIndices, containsValidData, detectorBB, featureVectors, fgList, posteriors, variances.
Referenced by tld::DetectorCascade::release, ~DetectionResult.