tld::EnsembleClassifier
const unsigned char* tld::EnsembleClassifier::img
bool tld::EnsembleClassifier::enabled
Referenced by tld::Config::configure, EnsembleClassifier, filter, learn.
int tld::EnsembleClassifier::numTrees
Referenced by classifyWindow, EnsembleClassifier, initFeatureLocations, initFeatureOffsets, initPosteriors, tld::DetectorCascade::propagateMembers, tld::TLD::readFromFile, tld::TLD::writeToFile.
int tld::EnsembleClassifier::numFeatures
Referenced by EnsembleClassifier, init, initFeatureLocations, initFeatureOffsets, tld::DetectorCascade::propagateMembers, tld::TLD::readFromFile, tld::TLD::writeToFile.
int tld::EnsembleClassifier::imgWidthStep
Referenced by initFeatureOffsets, tld::DetectorCascade::propagateMembers.
int tld::EnsembleClassifier::numScales
Referenced by initFeatureOffsets, tld::DetectorCascade::propagateMembers.
cv::Size* tld::EnsembleClassifier::scales
Referenced by initFeatureOffsets, tld::DetectorCascade::propagateMembers.
int* tld::EnsembleClassifier::windowOffsets
Referenced by tld::DetectorCascade::propagateMembers.
int* tld::EnsembleClassifier::featureOffsets
Referenced by initFeatureOffsets, release.
float* tld::EnsembleClassifier::features
Referenced by initFeatureLocations, initFeatureOffsets, tld::TLD::readFromFile, release, tld::TLD::writeToFile.
int tld::EnsembleClassifier::numIndices
Referenced by init, initPosteriors, tld::TLD::readFromFile, updatePosterior, tld::TLD::writeToFile.
float* tld::EnsembleClassifier::posteriors
Referenced by initPosteriors, release, updatePosterior.
int* tld::EnsembleClassifier::positives
Referenced by initPosteriors, release, updatePosterior, tld::TLD::writeToFile.
int* tld::EnsembleClassifier::negatives
Referenced by initPosteriors, release, updatePosterior, tld::TLD::writeToFile.
DetectionResult* tld::EnsembleClassifier::detectionResult
Referenced by classifyWindow, filter, tld::DetectorCascade::propagateMembers.
float tld::EnsembleClassifier::calcConfidence(int *featureVector)
int tld::EnsembleClassifier::calcFernFeature(int windowIdx, int treeIdx)
void tld::EnsembleClassifier::calcFeatureVector(int windowIdx, int *featureVector)
void tld::EnsembleClassifier::updatePosteriors(int *featureVector, int positive, int amount)
tld::EnsembleClassifier::EnsembleClassifier()
References enabled, numFeatures, numTrees.
tld::EnsembleClassifier::~EnsembleClassifier()
References release.
void tld::EnsembleClassifier::init()
References initFeatureLocations, initFeatureOffsets, initPosteriors, numFeatures, numIndices.
Referenced by tld::DetectorCascade::init.
void tld::EnsembleClassifier::initFeatureLocations()
References features, numFeatures, numTrees.
Referenced by init.
void tld::EnsembleClassifier::initFeatureOffsets()
References featureOffsets, features, imgWidthStep, numFeatures, numScales, numTrees, scales, sub2idx.
Referenced by init, tld::TLD::readFromFile.
void tld::EnsembleClassifier::initPosteriors()
References negatives, numIndices, numTrees, positives, posteriors.
Referenced by init, tld::TLD::readFromFile.
void tld::EnsembleClassifier::release()
References featureOffsets, features, negatives, positives, posteriors.
Referenced by tld::DetectorCascade::release, ~EnsembleClassifier.
void tld::EnsembleClassifier::nextIteration(const cv::Mat &img)
void tld::EnsembleClassifier::classifyWindow(int windowIdx)
References detectionResult, tld::DetectionResult::featureVectors, numTrees, tld::DetectionResult::posteriors.
Referenced by filter.
void tld::EnsembleClassifier::updatePosterior(int treeIdx, int idx, int positive, int amount)
References negatives, numIndices, positives, posteriors.
Referenced by tld::TLD::readFromFile.
void tld::EnsembleClassifier::learn(int *boundary, int positive, int *featureVector)
References enabled.
bool tld::EnsembleClassifier::filter(int i)
References classifyWindow, detectionResult, enabled, tld::DetectionResult::posteriors.