tld::DetectorCascade
int tld::DetectorCascade::numScales
cv::Size* tld::DetectorCascade::scales
int tld::DetectorCascade::minScale
Referenced by tld::Config::configure, DetectorCascade, initWindowsAndScales.
int tld::DetectorCascade::maxScale
Referenced by tld::Config::configure, DetectorCascade, initWindowsAndScales.
bool tld::DetectorCascade::useShift
Referenced by tld::Config::configure, DetectorCascade, initWindowsAndScales.
float tld::DetectorCascade::shift
Referenced by tld::Config::configure, DetectorCascade, initWindowsAndScales.
int tld::DetectorCascade::minSize
Referenced by tld::Config::configure, DetectorCascade, initWindowsAndScales, propagateMembers.
int tld::DetectorCascade::numFeatures
Referenced by tld::Config::configure, DetectorCascade, initWindowOffsets, propagateMembers, tld::TLD::readFromFile, tld::TLD::writeToFile.
int tld::DetectorCascade::numTrees
Referenced by tld::Config::configure, DetectorCascade, initWindowOffsets, propagateMembers, tld::TLD::readFromFile, tld::TLD::writeToFile.
int tld::DetectorCascade::imgWidth
Referenced by DetectorCascade, Main::doWork, init, initWindowsAndScales.
int tld::DetectorCascade::imgHeight
Referenced by DetectorCascade, Main::doWork, init, initWindowsAndScales.
int tld::DetectorCascade::imgWidthStep
Referenced by DetectorCascade, Main::doWork, init, initWindowOffsets, propagateMembers.
int tld::DetectorCascade::objWidth
Referenced by DetectorCascade, init, initWindowsAndScales, tld::TLD::readFromFile, release, tld::TLD::writeToFile.
int tld::DetectorCascade::objHeight
Referenced by DetectorCascade, init, initWindowsAndScales, tld::TLD::readFromFile, release, tld::TLD::writeToFile.
int tld::DetectorCascade::numWindows
Referenced by Main::doWork, initWindowOffsets, initWindowsAndScales, propagateMembers, release.
int* tld::DetectorCascade::windows
Referenced by initWindowOffsets, initWindowsAndScales, propagateMembers, release.
int* tld::DetectorCascade::windowOffsets
Referenced by initWindowOffsets, propagateMembers, release.
bool tld::DetectorCascade::initialised
Referenced by DetectorCascade, init, tld::TLD::readFromFile, release.
ForegroundDetector* tld::DetectorCascade::foregroundDetector
Referenced by DetectorCascade, Main::doWork, propagateMembers, release, ~DetectorCascade.
VarianceFilter* tld::DetectorCascade::varianceFilter
Referenced by tld::Config::configure, DetectorCascade, propagateMembers, tld::TLD::readFromFile, tld::TLD::writeToFile, ~DetectorCascade.
EnsembleClassifier* tld::DetectorCascade::ensembleClassifier
Referenced by tld::Config::configure, DetectorCascade, init, propagateMembers, tld::TLD::readFromFile, release, tld::TLD::writeToFile, ~DetectorCascade.
Clustering* tld::DetectorCascade::clustering
Referenced by DetectorCascade, propagateMembers, release.
NNClassifier* tld::DetectorCascade::nnClassifier
Referenced by tld::Config::configure, DetectorCascade, propagateMembers, tld::TLD::readFromFile, release, tld::TLD::TLD, tld::TLD::writeToFile, ~DetectorCascade.
DetectionResult* tld::DetectorCascade::detectionResult
Referenced by cleanPreviousData, DetectorCascade, Main::doWork, propagateMembers, release, ~DetectorCascade.
void tld::DetectorCascade::propagateMembers()
References clustering, tld::Clustering::detectionResult, tld::NNClassifier::detectionResult, tld::EnsembleClassifier::detectionResult, tld::VarianceFilter::detectionResult, tld::ForegroundDetector::detectionResult, detectionResult, ensembleClassifier, foregroundDetector, imgWidthStep, tld::EnsembleClassifier::imgWidthStep, tld::DetectionResult::init, tld::ForegroundDetector::minBlobSize, minSize, nnClassifier, numFeatures, tld::EnsembleClassifier::numFeatures, tld::EnsembleClassifier::numScales, tld::EnsembleClassifier::numTrees, numTrees, tld::Clustering::numWindows, numWindows, tld::EnsembleClassifier::scales, varianceFilter, tld::EnsembleClassifier::windowOffsets, windowOffsets, tld::VarianceFilter::windowOffsets, tld::Clustering::windows, windows, tld::NNClassifier::windows.
Referenced by init, tld::TLD::readFromFile.
tld::DetectorCascade::DetectorCascade()
References clustering, detectionResult, ensembleClassifier, foregroundDetector, imgHeight, imgWidth, imgWidthStep, initialised, maxScale, minScale, minSize, nnClassifier, numFeatures, numTrees, objHeight, objWidth, shift, useShift, varianceFilter.
tld::DetectorCascade::~DetectorCascade()
References detectionResult, ensembleClassifier, foregroundDetector, nnClassifier, release, varianceFilter.
void tld::DetectorCascade::init()
References ensembleClassifier, imgHeight, imgWidth, imgWidthStep, tld::EnsembleClassifier::init, initialised, initWindowOffsets, initWindowsAndScales, objHeight, objWidth, propagateMembers.
void tld::DetectorCascade::initWindowOffsets()
References imgWidthStep, numFeatures, numTrees, numWindows, sub2idx, windowOffsets, windows.
Referenced by init, tld::TLD::readFromFile.
void tld::DetectorCascade::initWindowsAndScales()
References imgHeight, imgWidth, maxScale, minScale, minSize, numWindows, objHeight, objWidth, shift, useShift, windows.
Referenced by init, tld::TLD::readFromFile.
void tld::DetectorCascade::release()
References clustering, detectionResult, ensembleClassifier, foregroundDetector, initialised, nnClassifier, numWindows, objHeight, objWidth, tld::DetectionResult::release, tld::Clustering::release, tld::NNClassifier::release, tld::EnsembleClassifier::release, tld::ForegroundDetector::release, windowOffsets, windows.
Referenced by tld::TLD::release, ~DetectorCascade.
void tld::DetectorCascade::cleanPreviousData()
References detectionResult, tld::DetectionResult::reset.
void tld::DetectorCascade::detect(const cv::Mat &img)