CBlobContour
friend class CBlob
friend class CBlobProperties
t_chainCodeList CBlobContour::m_contour
Crack code list.
Referenced by AddChainCode, CBlobContour, GetChainCode, GetContourPoints, IsEmpty, CBlob::IsEmpty, operator=, CBlob::operator=, ResetChainCode, ~CBlobContour.
CvPoint CBlobContour::m_startPoint
Starting point of the contour.
t_PointList CBlobContour::m_contourPoints
All points from the contour.
double CBlobContour::m_area
Computed area from contour.
double CBlobContour::m_perimeter
Computed perimeter from contour.
CvMoments CBlobContour::m_moments
Computed moments from contour.
CvMemStorage* CBlobContour::m_parentStorage
Pointer to storage.
CBlobContour::CBlobContour()
Constructors.
References m_contour.
CBlobContour::CBlobContour(CvPoint startPoint, CvMemStorage *storage)
References m_contour.
CBlobContour::CBlobContour(CBlobContour *source)
Copy constructor.
References NULL.
CBlobContour::~CBlobContour()
References m_contour.
CBlobContour & CBlobContour::operator=(const CBlobContour &source)
Assigment operator.
Copy operator.
References m_contour.
void CBlobContour::AddChainCode(t_chainCode code)
Add chain code to contour.
FUNCIÓ: AddChainCodeFUNCIONALITAT: Add chain code to contourPARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/05/06MODIFICACIÓ: Data. Autor. Descripció.
References m_contour.
Referenced by contourTracing.
t_chainCodeList CBlobContour::GetChainCode()
Return freeman chain coded contour.
References m_contour.
Referenced by CBlob::JoinBlob.
bool CBlobContour::IsEmpty()
References m_contour, NULL.
Referenced by GetArea, GetMoment, GetPerimeter.
t_PointList CBlobContour::GetContourPoints()
Return all contour points.
Calculate contour points from crack codes.
References m_contour, NULL.
Referenced by CBlob::ExternPerimeter, CBlob::FillBlob, GetArea, CBlob::GetBoundingBox, CBlob::GetConvexHull, GetMoment, GetPerimeter, CBlob::Mean, CBlobGetXYInside::operator(), CBlobGetMaxYatMinX::operator(), CBlobGetMaxXatMaxY::operator(), CBlobGetMinYatMaxX::operator(), CBlobGetMinXatMinY::operator().
CvPoint CBlobContour::GetStartPoint() const
Referenced by CBlob::operator=.
void CBlobContour::ResetChainCode()
Clears chain code contour.
Clears chain code contour and points.
References m_contour.
double CBlobContour::GetArea()
Computes area from contour.
FUNCIÓ: GetAreaFUNCIONALITAT: Computes area from chain codePARÀMETRES: RESULTAT: May give negative areas for clock wise contours RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/30MODIFICACIÓ: Data. Autor. Descripció.NOTA: Algorithm derived from "Properties of contour codes", G.R. Wilson
References GetContourPoints, IsEmpty.
Referenced by CBlob::Area, CBlobProperties::GetArea.
double CBlobContour::GetPerimeter()
Computes perimeter from contour.
FUNCIÓ: GetPerimeterFUNCIONALITAT: Get perimeter from chain code. Diagonals sum sqrt(2) and horizontal and vertical codes 1PARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/30MODIFICACIÓ: Data. Autor. Descripció.NOTA: Algorithm derived from "Methods to estimate area and perimeters of blob-like objects: A comparison", L.Yang
References GetContourPoints, IsEmpty.
Referenced by CBlobProperties::GetPerimeter, CBlob::Perimeter.
double CBlobContour::GetMoment(int p, int q)
Get contour moment (p,q up to MAX_CALCULATED_MOMENTS).
References GetContourPoints, IsEmpty, MAX_MOMENTS_ORDER.
Referenced by CBlob::Moment.