tld::Trajectory
std::size_t tld::Trajectory::m_length
number of the last frames which are considered by the trajectory
std::vector<CvPoint> tld::Trajectory::m_track_positions
vector containing the locations of the points
std::vector<CvScalar> tld::Trajectory::m_track_colors
vector containing the colors of the points
tld::Trajectory::Trajectory()
Constructor; don't forget to call init(length) afterwards
tld::Trajectory::~Trajectory()
Destructor
void tld::Trajectory::init(std::size_t length)
Initializes the trajectory. length specifies the number of the last frames which are considered by the trajectory
Referenced by Main::doWork.
void tld::Trajectory::addPoint(CvPoint point, CvScalar color)
Adds a new point to the trajectory. If you want to add a "place holder" point just add a cvPoint(-1, -1) and cvScalar(-1 , -1, -1) point point which specifies the location of the point color defines the color (confidence) of the point
Referenced by Main::doWork.
void tld::Trajectory::drawTrajectory(IplImage *image)
Draws the trajectory into an image. image image to draw
Referenced by Main::doWork.