libconfig::Setting
Type
Format
friend class Config
config_setting_t* libconfig::Setting::_setting
Type libconfig::Setting::_type
Format libconfig::Setting::_format
libconfig::Setting::Setting(config_setting_t *setting)
void libconfig::Setting::assertType(Type type) const
libconfig::Setting::Setting(const Setting &other)
Setting& libconfig::Setting::operator=(const Setting &other)
Setting & libconfig::Setting::wrapSetting(config_setting_t *setting)
libconfig::Setting::~Setting()
Type libconfig::Setting::getType() const
Format libconfig::Setting::getFormat() const
void libconfig::Setting::setFormat(Format format)
libconfig::Setting::operator bool() const
libconfig::Setting::operator int() const
References config_setting_get_bool, TypeBoolean.
Referenced by operator unsigned long.
libconfig::Setting::operator unsigned int() const
References config_setting_get_int, TypeInt.
Referenced by operator long long.
libconfig::Setting::operator long() const
libconfig::Setting::operator unsigned long() const
References operator int, operator long long.
libconfig::Setting::operator long long() const
References operator unsigned int, operator unsigned long long.
Referenced by operator unsigned long.
libconfig::Setting::operator unsigned long long() const
References config_setting_get_int64, TypeInt64.
Referenced by operator long long.
libconfig::Setting::operator double() const
libconfig::Setting::operator float() const
References config_setting_get_float, TypeFloat.
libconfig::Setting::operator const char *() const
References config_setting_get_float, TypeFloat.
libconfig::Setting::operator std::string() const
References config_setting_get_string, TypeString.
const char* libconfig::Setting::c_str() const
Setting & libconfig::Setting::operator=(bool value)
Setting & libconfig::Setting::operator=(int value)
References config_setting_set_bool.
Setting & libconfig::Setting::operator=(long value)
References config_setting_set_int.
Setting & libconfig::Setting::operator=(const long long &value)
Setting & libconfig::Setting::operator=(const double &value)
References config_setting_set_int64.
Setting & libconfig::Setting::operator=(float value)
References config_setting_set_float.
Setting & libconfig::Setting::operator=(const char *value)
References config_setting_set_float.
Setting & libconfig::Setting::operator=(const std::string &value)
References config_setting_set_string.
Setting & libconfig::Setting::operator[](const char *key) const
Setting& libconfig::Setting::operator[](const std::string &key) const
Setting & libconfig::Setting::operator[](int index) const
References config_setting_set_string.
bool libconfig::Setting::lookupValue(const char *name, bool &value) const
bool libconfig::Setting::lookupValue(const char *name, int &value) const
bool libconfig::Setting::lookupValue(const char *name, unsigned int &value) const
bool libconfig::Setting::lookupValue(const char *name, long long &value) const
bool libconfig::Setting::lookupValue(const char *name, unsigned long long &value) const
bool libconfig::Setting::lookupValue(const char *name, double &value) const
bool libconfig::Setting::lookupValue(const char *name, float &value) const
bool libconfig::Setting::lookupValue(const char *name, const char *&value) const
bool libconfig::Setting::lookupValue(const char *name, std::string &value) const
bool libconfig::Setting::lookupValue(const std::string &name, bool &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, int &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, unsigned int &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, long long &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, unsigned long long &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, double &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, float &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, const char *&value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Setting::lookupValue(const std::string &name, std::string &value) const
References lookupValue.
Referenced by lookupValue.
void libconfig::Setting::remove(const char *name)
void libconfig::Setting::remove(const std::string &name)
void libconfig::Setting::remove(unsigned int idx)
References config_setting_remove.
Setting& libconfig::Setting::add(const std::string &name, Type type)
References add.
Referenced by add.
Setting & libconfig::Setting::add(const char *name, Type type)
References config_setting_remove_elem.
Setting & libconfig::Setting::add(Type type)
bool libconfig::Setting::exists(const std::string &name) const
References exists.
Referenced by exists.
bool libconfig::Setting::exists(const char *name) const
int libconfig::Setting::getLength() const
References config_setting_get_member.
const char * libconfig::Setting::getName() const
std::string libconfig::Setting::getPath() const
int libconfig::Setting::getIndex() const
const Setting & libconfig::Setting::getParent() const
Setting & libconfig::Setting::getParent()
References config_setting_parent.
bool libconfig::Setting::isRoot() const
bool libconfig::Setting::isGroup() const
bool libconfig::Setting::isArray() const
bool libconfig::Setting::isList() const
bool libconfig::Setting::isAggregate() const
bool libconfig::Setting::isScalar() const
bool libconfig::Setting::isNumber() const
unsigned int libconfig::Setting::getSourceLine() const
References config_setting_parent.
const char * libconfig::Setting::getSourceFile() const