tld::Gui
std::string tld::Gui::m_window_name
tld::Gui::Gui()
tld::Gui::~Gui()
void tld::Gui::init()
Referenced by main.
void tld::Gui::showImage(IplImage *image)
Referenced by Main::doWork.
char tld::Gui::getKey()
Referenced by Main::doWork.
std::string tld::Gui::windowName()