libconfig::Config
config_t* libconfig::Config::_config
Setting::Format libconfig::Config::_defaultFormat
void libconfig::Config::ConfigDestructor(void *arg)
libconfig::Config::Config(const Config &other)
Config& libconfig::Config::operator=(const Config &other)
void libconfig::Config::handleError() const
libconfig::Config::Config()
libconfig::Config::~Config()
References config_init, config_set_destructor.
void libconfig::Config::setAutoConvert(bool flag)
bool libconfig::Config::getAutoConvert() const
void libconfig::Config::setDefaultFormat(Setting::Format format)
Setting::Format libconfig::Config::getDefaultFormat() const
void libconfig::Config::setTabWidth(unsigned short width)
References libconfig::Setting::FormatHex.
unsigned short libconfig::Config::getTabWidth() const
void libconfig::Config::setIncludeDir(const char *includeDir)
const char * libconfig::Config::getIncludeDir() const
void libconfig::Config::read(FILE *stream)
void libconfig::Config::write(FILE *stream) const
void libconfig::Config::readString(const char *str)
void libconfig::Config::readString(const std::string &str)
References readString.
Referenced by readString.
void libconfig::Config::readFile(const char *filename)
Referenced by tld::Config::init.
void libconfig::Config::writeFile(const char *filename)
References config_read_file.
Setting& libconfig::Config::lookup(const std::string &path) const
References lookup.
Referenced by tld::Config::init, lookup.
Setting & libconfig::Config::lookup(const char *path) const
bool libconfig::Config::exists(const std::string &path) const
References exists.
Referenced by exists.
bool libconfig::Config::exists(const char *path) const
References config_lookup.
bool libconfig::Config::lookupValue(const char *path, bool &value) const
Referenced by tld::Config::init.
bool libconfig::Config::lookupValue(const char *path, int &value) const
bool libconfig::Config::lookupValue(const char *path, unsigned int &value) const
bool libconfig::Config::lookupValue(const char *path, long long &value) const
bool libconfig::Config::lookupValue(const char *path, unsigned long long &value) const
bool libconfig::Config::lookupValue(const char *path, double &value) const
bool libconfig::Config::lookupValue(const char *path, float &value) const
bool libconfig::Config::lookupValue(const char *path, const char *&value) const
bool libconfig::Config::lookupValue(const char *path, std::string &value) const
bool libconfig::Config::lookupValue(const std::string &path, bool &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, int &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, unsigned int &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, long long &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, unsigned long long &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, double &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, float &value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, const char *&value) const
References lookupValue.
Referenced by lookupValue.
bool libconfig::Config::lookupValue(const std::string &path, std::string &value) const
References lookupValue.
Referenced by lookupValue.
Setting & libconfig::Config::getRoot() const