tld::TLD
bool tld::TLD::trackerEnabled
Referenced by tld::Config::configure, TLD.
bool tld::TLD::detectorEnabled
Referenced by TLD.
bool tld::TLD::learningEnabled
Referenced by tld::Config::configure, Main::doWork, TLD.
bool tld::TLD::alternating
Referenced by tld::Config::configure, Main::doWork, TLD.
MedianFlowTracker* tld::TLD::medianFlowTracker
Referenced by release, TLD, ~TLD.
DetectorCascade* tld::TLD::detectorCascade
Referenced by tld::Config::configure, Main::doWork, readFromFile, release, TLD, writeToFile, ~TLD.
NNClassifier* tld::TLD::nnClassifier
Referenced by TLD.
bool tld::TLD::valid
Referenced by TLD.
bool tld::TLD::wasValid
Referenced by TLD.
cv::Mat tld::TLD::prevImg
cv::Mat tld::TLD::currImg
cv::Rect* tld::TLD::prevBB
Referenced by TLD.
cv::Rect* tld::TLD::currBB
Referenced by Main::doWork, release, TLD.
float tld::TLD::currConf
Referenced by Main::doWork.
bool tld::TLD::learning
Referenced by Main::doWork, TLD.
void tld::TLD::storeCurrentData()
void tld::TLD::fuseHypotheses()
void tld::TLD::learn()
void tld::TLD::initialLearning()
tld::TLD::TLD()
References alternating, currBB, detectorCascade, detectorEnabled, learning, learningEnabled, medianFlowTracker, tld::DetectorCascade::nnClassifier, nnClassifier, prevBB, trackerEnabled, valid, wasValid.
tld::TLD::~TLD()
References detectorCascade, medianFlowTracker.
void tld::TLD::release()
References tld::MedianFlowTracker::cleanPreviousData, currBB, detectorCascade, medianFlowTracker, tld::DetectorCascade::release.
Referenced by Main::doWork, readFromFile.
void tld::TLD::selectObject(const cv::Mat &img, cv::Rect *bb)
Referenced by Main::doWork.
void tld::TLD::processImage(const cv::Mat &img)
Referenced by Main::doWork.
void tld::TLD::writeToFile(const char *path)
References detectorCascade, tld::DetectorCascade::ensembleClassifier, tld::NNClassifier::falsePositives, tld::EnsembleClassifier::features, tld::TldExportEntry::index, tld::VarianceFilter::minVar, tld::TldExportEntry::N, tld::EnsembleClassifier::negatives, tld::DetectorCascade::nnClassifier, tld::DetectorCascade::numFeatures, tld::EnsembleClassifier::numFeatures, tld::EnsembleClassifier::numIndices, tld::DetectorCascade::numTrees, tld::EnsembleClassifier::numTrees, tld::DetectorCascade::objHeight, tld::DetectorCascade::objWidth, tld::TldExportEntry::P, tld::EnsembleClassifier::positives, tld::NNClassifier::truePositives, tld::DetectorCascade::varianceFilter.
Referenced by Main::doWork.
void tld::TLD::readFromFile(const char *path)
References detectorCascade, tld::DetectorCascade::ensembleClassifier, tld::NNClassifier::falsePositives, tld::EnsembleClassifier::features, tld::TldExportEntry::index, tld::EnsembleClassifier::initFeatureOffsets, tld::DetectorCascade::initialised, tld::EnsembleClassifier::initPosteriors, tld::DetectorCascade::initWindowOffsets, tld::DetectorCascade::initWindowsAndScales, tld::VarianceFilter::minVar, tld::TldExportEntry::N, tld::DetectorCascade::nnClassifier, NULL, tld::DetectorCascade::numFeatures, tld::EnsembleClassifier::numFeatures, tld::EnsembleClassifier::numIndices, tld::DetectorCascade::numTrees, tld::EnsembleClassifier::numTrees, tld::DetectorCascade::objHeight, tld::DetectorCascade::objWidth, tld::TldExportEntry::P, tld::DetectorCascade::propagateMembers, release, TLD_PATCH_SIZE, tld::NNClassifier::truePositives, tld::EnsembleClassifier::updatePosterior, tld::NormalizedPatch::values, tld::DetectorCascade::varianceFilter.
Referenced by Main::doWork.