CBlob
typedef std::list<CBlobContour> CBlob::t_contourList
CvMemStorage* CBlob::m_storage
Contour storage memory.
CBlobContour CBlob::m_externalContour
External contour of the blob (crack codes).
t_contourList CBlob::m_internalContours
Internal contours (crack codes).
t_labelType CBlob::m_id
Label number.
double CBlob::m_area
Area.
double CBlob::m_perimeter
Perimeter.
double CBlob::m_externPerimeter
Extern perimeter from blob.
double CBlob::m_meanGray
Mean gray color.
double CBlob::m_stdDevGray
Standard deviation from gray color blob distribution.
CvRect CBlob::m_boundingBox
Bounding box.
CvBox2D CBlob::m_ellipse
Bounding ellipse.
CvSize CBlob::m_originalImageSize
Sizes from image where blob is extracted.
CBlob::CBlob()
CBlob::CBlob(t_labelType id, CvPoint startPoint, CvSize originalImageSize)
CBlob::~CBlob()
CBlob::CBlob(const CBlob &src)
Copy constructor.
CBlob::CBlob(const CBlob *src)
References NULL.
CBlob & CBlob::operator=(const CBlob &src)
Operador d'assignació Assigment operator
References CBlobContour::GetStartPoint, CBlobContour::m_contour.
void CBlob::AddInternalContour(const CBlobContour &newContour)
Adds a new internal contour to the blob.
Referenced by ComponentLabeling.
CBlobContour* CBlob::GetExternalContour()
Retrieves contour in Freeman's chain code.
Referenced by ComponentLabeling, IsEmpty, JoinBlob, CBlobGetXYInside::operator(), CBlobGetMaxYatMinX::operator(), CBlobGetMaxXatMaxY::operator(), CBlobGetMinYatMaxX::operator(), CBlobGetMinXatMinY::operator().
CvMemStorage* CBlob::GetStorage()
Retrieves blob storage.
Referenced by ComponentLabeling.
t_labelType CBlob::GetID()
Get label ID.
Referenced by CBlobGetID::operator().
int CBlob::Exterior(IplImage *mask, bool xBorder=true, bool yBorder=true)
> 0 for extern blobs, 0 if not
FUNCIÓ: ExteriorFUNCIONALITAT: Return true for extern blobsPARÀMETRES: xBorder: true to consider blobs touching horizontal borders as externyBorder: true to consider blobs touching vertical borders as extern RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/05/06MODIFICACIÓ: Data. Autor. Descripció.
References ExternPerimeter.
Referenced by CBlobGetExterior::operator().
double CBlob::Area()
Compute blob's area.
FUNCIÓ: AreaFUNCIONALITAT: Get blob area, ie. external contour area minus internal contours areaPARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/30MODIFICACIÓ: Data. Autor. Descripció.
References CBlobContour::GetArea.
Referenced by CBlobGetAreaElipseRatio::operator(), CBlobGetArea::operator(), CBlobGetBreadth::operator(), CBlobGetLength::operator(), CBlobGetCompactness::operator(), CBlobGetElongation::operator().
double CBlob::Perimeter()
Compute blob's perimeter.
FUNCIÓ: PerimeterFUNCIONALITAT: Get blob perimeter, ie. sum of the lenght of all the contoursPARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/04/30MODIFICACIÓ: Data. Autor. Descripció.
References CBlobContour::GetPerimeter.
Referenced by CBlobGetExternPerimeterRatio::operator(), CBlobGetPerimeter::operator(), CBlobGetBreadth::operator(), CBlobGetLength::operator(), CBlobGetRoughness::operator(), CBlobGetCompactness::operator(), CBlobGetElongation::operator().
double CBlob::Moment(int p, int q)
Compute blob's moment (p,q up to MAX_CALCULATED_MOMENTS).
References CBlobContour::GetMoment.
Referenced by GetEllipse, CBlobGetMoment::operator().
double CBlob::ExternPerimeter(IplImage *mask, bool xBorder=true, bool yBorder=true)
Compute extern perimeter.
FUNCIÓ: ExternPerimeterFUNCIONALITAT: Get extern perimeter (perimeter touching image borders)PARÀMETRES: maskImage: if != NULL, counts maskImage black pixels as external pixels and contour points touching them are counted as external contour points.xBorder: true to consider blobs touching horizontal borders as externyBorder: true to consider blobs touching vertical borders as extern RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/05/05MODIFICACIÓ: Data. Autor. Descripció.NOTA: If CBlobContour::GetContourPoints aproximates contours with a method different that NONE, this function will not give correct results
References CBlobContour::GetContourPoints, NULL.
Referenced by Exterior, CBlobGetExternHullPerimeterRatio::operator(), CBlobGetExternPerimeterRatio::operator(), CBlobGetExternPerimeter::operator().
double CBlob::Mean(IplImage *image)
Get mean grey color.
FUNCIÓ: MeanFUNCIONALITAT: Get blob mean color in input imagePARÀMETRES: image: image from gray color are extracted RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/05/06MODIFICACIÓ: Data. Autor. Descripció.
References GetBoundingBox, CBlobContour::GetContourPoints.
Referenced by CBlobGetMean::operator(), StdDev.
double CBlob::StdDev(IplImage *image)
Get standard deviation grey color.
References Mean.
Referenced by CBlobGetStdDev::operator().
bool CBlob::IsEmpty()
Indica si el blob està buit ( no té cap info associada ) Shows if the blob has associated information
References GetExternalContour, CBlobContour::m_contour.
t_PointList CBlob::GetConvexHull()
Retorna el poligon convex del blob Calculates the convex hull of the blob FUNCTION: GetConvexHullFUNCTIONALITY: Calculates the convex hull polygon of the blobPARAMETERS: dst: where to store the result RESULT: true if no error ocurred RESTRICTIONS:AUTHOR: Ricard BorràsCREATION DATE: 25-05-2005.MODIFICATION: Date. Author. Description.
References CBlobContour::GetContourPoints.
Referenced by CBlobGetHullArea::operator(), CBlobGetHullPerimeter::operator().
void CBlob::FillBlob(IplImage *imatge, CvScalar color, int offsetX=0, int offsetY=0)
Pinta l'interior d'un blob d'un color determinat Paints the blob in an image FUNCTION: FillBlobFUNCTIONALITY: Fills the blob with a specified colour PARAMETERS: imatge: where to paintcolor: colour to paint the blob RESULT: modifies input image and returns the seed point used to fill the blob RESTRICTIONS:AUTHOR: Ricard BorràsCREATION DATE: 25-05-2005.MODIFICATION: Date. Author. Description.
References CBlobContour::GetContourPoints.
void CBlob::JoinBlob(CBlob *blob)
Join a blob to current one (add's contour.
FUNCTION: JoinBlobFUNCTIONALITY: Add's external contour to current external contourPARAMETERS: blob: blob from which extract the added external contour RESULT: true if no error ocurred RESTRICTIONS: Only external contours are addedAUTHOR: Ricard BorràsCREATION DATE: 25-05-2005.MODIFICATION: Date. Author. Description.
References CBlobContour::GetChainCode, GetExternalContour.
CvRect CBlob::GetBoundingBox()
Get bounding box.
FUNCIÓ: GetBoundingBoxFUNCIONALITAT: Get bounding box (without rotation) of a blobPARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/05/06MODIFICACIÓ: Data. Autor. Descripció.
References CBlobContour::GetContourPoints.
Referenced by MaxX, MaxY, Mean, MinX, MinY, CBlobGetDiffY::operator(), CBlobGetDiffX::operator().
CvBox2D CBlob::GetEllipse()
Get bounding ellipse.
FUNCIÓ: GetEllipseFUNCIONALITAT: Calculates bounding ellipse of external contour pointsPARÀMETRES: RESULTAT: RESTRICCIONS: AUTOR: rborrasDATA DE CREACIÓ: 2008/05/06MODIFICACIÓ: Data. Autor. Descripció.NOTA: Calculation is made using second order moment aproximation
References Moment.
Referenced by CBlobGetOrientation::operator(), CBlobGetMinorAxisLength::operator(), CBlobGetAreaElipseRatio::operator(), CBlobGetMajorAxisLength::operator().
double CBlob::MinX()
Minimun X.
References GetBoundingBox.
Referenced by CBlobGetXCenter::operator(), CBlobGetMinX::operator(), CBlobGetMaxYatMinX::operator().
double CBlob::MinY()
Minimun Y.
References GetBoundingBox.
Referenced by CBlobGetYCenter::operator(), CBlobGetMinY::operator(), CBlobGetMinXatMinY::operator().
double CBlob::MaxX()
Maximun X.
References GetBoundingBox.
Referenced by CBlobGetXCenter::operator(), CBlobGetMaxX::operator(), CBlobGetMinYatMaxX::operator().
double CBlob::MaxY()
Maximun Y.
References GetBoundingBox.
Referenced by CBlobGetYCenter::operator(), CBlobGetMaxY::operator(), CBlobGetMaxXatMaxY::operator().
void CBlob::ClearContours()
Deallocates all contours.