libconfig.h
LIBCONFIG_API
LIBCONFIG_VER_MAJOR
LIBCONFIG_VER_MINOR
LIBCONFIG_VER_REVISION
CONFIG_TYPE_NONE
Referenced by config_setting_add, config_setting_set_bool, config_setting_set_float, config_setting_set_int, config_setting_set_int64, config_setting_set_string, yyparse.
CONFIG_TYPE_GROUP
Referenced by config_setting_get_elem, config_setting_get_member, config_setting_length, config_setting_remove, config_setting_remove_elem, yyparse.
CONFIG_TYPE_INT
Referenced by config_setting_set_float, config_setting_set_format, config_setting_set_int, config_setting_set_int64, config_setting_set_int_elem.
CONFIG_TYPE_INT64
Referenced by config_setting_set_float, config_setting_set_format, config_setting_set_int64, config_setting_set_int64_elem.
CONFIG_TYPE_FLOAT
Referenced by config_setting_set_float, config_setting_set_float_elem, config_setting_set_int, config_setting_set_int64.
CONFIG_TYPE_STRING
Referenced by config_lookup_string, config_setting_get_string, config_setting_get_string_elem, config_setting_lookup_string, config_setting_set_string, config_setting_set_string_elem.
CONFIG_TYPE_BOOL
Referenced by config_lookup_bool, config_setting_get_bool, config_setting_get_bool_elem, config_setting_lookup_bool, config_setting_set_bool, config_setting_set_bool_elem.
CONFIG_TYPE_ARRAY
Referenced by config_setting_add, config_setting_get_elem, config_setting_length, config_setting_remove_elem, config_setting_set_bool_elem, config_setting_set_float_elem, config_setting_set_int64_elem, config_setting_set_int_elem, config_setting_set_string_elem, yyparse.
CONFIG_TYPE_LIST
Referenced by config_setting_add, config_setting_get_elem, config_setting_length, config_setting_remove_elem, config_setting_set_bool_elem, config_setting_set_float_elem, config_setting_set_int64_elem, config_setting_set_int_elem, config_setting_set_string_elem, yyparse.
CONFIG_FORMAT_DEFAULT
Referenced by config_setting_set_format, yyparse.
CONFIG_FORMAT_HEX
Referenced by config_setting_set_format, yyparse.
CONFIG_OPTION_AUTOCONVERT
Referenced by config_get_auto_convert, config_setting_set_float.
CONFIG_TRUE
Referenced by config_lookup_bool, config_lookup_string, config_setting_lookup_bool, config_setting_lookup_string, config_setting_remove, config_setting_remove_elem, config_setting_set_bool, config_setting_set_float, config_setting_set_format, config_setting_set_int, config_setting_set_int64, config_setting_set_string, config_write_file.
CONFIG_FALSE
Referenced by config_lookup_bool, config_lookup_float, config_lookup_int, config_lookup_int64, config_lookup_string, config_read_file, config_setting_get_bool_elem, config_setting_lookup_bool, config_setting_lookup_float, config_setting_lookup_int, config_setting_lookup_int64, config_setting_lookup_string, config_setting_remove, config_setting_remove_elem, config_setting_set_bool, config_setting_set_float, config_setting_set_format, config_setting_set_int, config_setting_set_int64, config_setting_set_string, config_write_file.
config_get_include_dir
config_setting_type
Referenced by config_lookup_bool, config_lookup_string, config_setting_lookup_bool, config_setting_lookup_string.
config_setting_is_group
config_setting_is_array
config_setting_is_list
config_setting_is_aggregate
config_setting_is_number
config_setting_is_scalar
config_setting_name
config_setting_parent
Referenced by libconfig::Setting::getParent, libconfig::Setting::getSourceLine.
config_setting_is_root
config_setting_get_hook
config_root_setting
config_set_default_format
config_get_default_format
config_set_tab_width
config_get_tab_width
config_setting_source_line
config_setting_source_file
config_error_text
config_error_file
config_error_line
config_error_type
config_error_t
typedef union config_value_t config_value_t
typedef struct config_setting_t config_setting_t
typedef struct config_list_t config_list_t
typedef struct config_t config_t
LIBCONFIG_API int config_read(config_t *config, FILE *stream)
References NULL.
LIBCONFIG_API void config_write(const config_t *config, FILE *stream)
References config_t::root, config_t::tab_width.
Referenced by config_write_file.
LIBCONFIG_API void config_set_default_format(config_t *config, short format)
LIBCONFIG_API void config_set_auto_convert(config_t *config, int flag)
References config_t::flags.
LIBCONFIG_API int config_get_auto_convert(const config_t *config)
References CONFIG_OPTION_AUTOCONVERT, config_t::flags.
Referenced by config_setting_set_int, config_setting_set_int64.
LIBCONFIG_API int config_read_string(config_t *config, const char *str)
References NULL.
LIBCONFIG_API int config_read_file(config_t *config, const char *filename)
References CONFIG_FALSE, config_t::error_text, config_t::error_type, NULL.
Referenced by libconfig::Config::writeFile.
LIBCONFIG_API int config_write_file(config_t *config, const char *filename)
References CONFIG_FALSE, CONFIG_TRUE, config_write, config_t::error_text, config_t::error_type.
LIBCONFIG_API void config_set_destructor(config_t *config, void(*destructor)(void *))
References config_t::destructor.
Referenced by libconfig::Config::~Config.
LIBCONFIG_API void config_set_include_dir(config_t *config, const char *include_dir)
References _delete, config_t::include_dir.
LIBCONFIG_API void config_init(config_t *config)
References _new.
Referenced by libconfig::Config::~Config.
LIBCONFIG_API void config_destroy(config_t *config)
References _delete, config_t::filenames, config_t::include_dir, config_t::num_filenames, config_t::root.
LIBCONFIG_API int config_setting_get_int(const config_setting_t *setting)
Referenced by config_setting_get_int_elem, libconfig::Setting::operator unsigned int.
LIBCONFIG_API long long config_setting_get_int64(const config_setting_t *setting)
Referenced by config_setting_get_int64_elem, libconfig::Setting::operator unsigned long long.
LIBCONFIG_API double config_setting_get_float(const config_setting_t *setting)
Referenced by config_setting_get_float_elem, libconfig::Setting::operator const char *, libconfig::Setting::operator float.
LIBCONFIG_API int config_setting_get_bool(const config_setting_t *setting)
References CONFIG_TYPE_BOOL, config_value_t::ival, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_bool, config_setting_lookup_bool, libconfig::Setting::operator int.
LIBCONFIG_API const char* config_setting_get_string(const config_setting_t *setting)
References CONFIG_TYPE_STRING, NULL, config_value_t::sval, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_string, config_setting_lookup_string, libconfig::Setting::operator std::string.
LIBCONFIG_API int config_setting_lookup_int(const config_setting_t *setting, const char *name, int *value)
References CONFIG_FALSE, config_setting_get_member.
LIBCONFIG_API int config_setting_lookup_int64(const config_setting_t *setting, const char *name, long long *value)
References CONFIG_FALSE, config_setting_get_member.
LIBCONFIG_API int config_setting_lookup_float(const config_setting_t *setting, const char *name, double *value)
References CONFIG_FALSE, config_setting_get_member.
LIBCONFIG_API int config_setting_lookup_bool(const config_setting_t *setting, const char *name, int *value)
References CONFIG_FALSE, config_setting_get_bool, config_setting_get_member, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_BOOL.
LIBCONFIG_API int config_setting_lookup_string(const config_setting_t *setting, const char *name, const char **value)
References CONFIG_FALSE, config_setting_get_member, config_setting_get_string, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_STRING.
LIBCONFIG_API int config_setting_set_int(config_setting_t *setting, int value)
References config_setting_t::config, CONFIG_FALSE, config_get_auto_convert, CONFIG_TRUE, CONFIG_TYPE_FLOAT, CONFIG_TYPE_INT, CONFIG_TYPE_NONE, config_value_t::fval, config_value_t::ival, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_int_elem, libconfig::Setting::operator=, yyparse.
LIBCONFIG_API int config_setting_set_int64(config_setting_t *setting, long long value)
References config_setting_t::config, CONFIG_FALSE, config_get_auto_convert, CONFIG_TRUE, CONFIG_TYPE_FLOAT, CONFIG_TYPE_INT, CONFIG_TYPE_INT64, CONFIG_TYPE_NONE, config_value_t::fval, INT32_MAX, INT32_MIN, config_value_t::ival, config_value_t::llval, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_int64_elem, libconfig::Setting::operator=, yyparse.
LIBCONFIG_API int config_setting_set_float(config_setting_t *setting, double value)
References config_setting_t::config, CONFIG_FALSE, CONFIG_OPTION_AUTOCONVERT, CONFIG_TRUE, CONFIG_TYPE_FLOAT, CONFIG_TYPE_INT, CONFIG_TYPE_INT64, CONFIG_TYPE_NONE, config_t::flags, config_value_t::fval, config_value_t::ival, config_value_t::llval, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_float_elem, libconfig::Setting::operator=, yyparse.
LIBCONFIG_API int config_setting_set_bool(config_setting_t *setting, int value)
References CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_BOOL, CONFIG_TYPE_NONE, config_value_t::ival, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_bool_elem, libconfig::Setting::operator=, yyparse.
LIBCONFIG_API int config_setting_set_string(config_setting_t *setting, const char *value)
References _delete, CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_NONE, CONFIG_TYPE_STRING, NULL, config_value_t::sval, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_string_elem, libconfig::Setting::operator=, libconfig::Setting::operator[], yyparse.
LIBCONFIG_API int config_setting_set_format(config_setting_t *setting, short format)
References CONFIG_FALSE, CONFIG_FORMAT_DEFAULT, CONFIG_FORMAT_HEX, CONFIG_TRUE, CONFIG_TYPE_INT, CONFIG_TYPE_INT64, config_setting_t::format, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API short config_setting_get_format(const config_setting_t *setting)
References config_setting_t::config, config_t::default_format, config_setting_t::format.
LIBCONFIG_API int config_setting_get_int_elem(const config_setting_t *setting, int idx)
References config_setting_get_elem, config_setting_get_int.
LIBCONFIG_API long long config_setting_get_int64_elem(const config_setting_t *setting, int idx)
References config_setting_get_elem, config_setting_get_int64.
LIBCONFIG_API double config_setting_get_float_elem(const config_setting_t *setting, int idx)
References config_setting_get_elem, config_setting_get_float.
LIBCONFIG_API int config_setting_get_bool_elem(const config_setting_t *setting, int idx)
References CONFIG_FALSE, config_setting_get_elem, CONFIG_TYPE_BOOL, config_value_t::ival, config_setting_t::type, config_setting_t::value.
LIBCONFIG_API const char* config_setting_get_string_elem(const config_setting_t *setting, int idx)
References config_setting_get_elem, CONFIG_TYPE_STRING, NULL, config_value_t::sval, config_setting_t::type, config_setting_t::value.
LIBCONFIG_API config_setting_t* config_setting_set_int_elem(config_setting_t *setting, int idx, int value)
References config_setting_get_elem, config_setting_set_int, CONFIG_TYPE_ARRAY, CONFIG_TYPE_INT, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API config_setting_t* config_setting_set_int64_elem(config_setting_t *setting, int idx, long long value)
References config_setting_get_elem, config_setting_set_int64, CONFIG_TYPE_ARRAY, CONFIG_TYPE_INT64, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API config_setting_t* config_setting_set_float_elem(config_setting_t *setting, int idx, double value)
References config_setting_get_elem, config_setting_set_float, CONFIG_TYPE_ARRAY, CONFIG_TYPE_FLOAT, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API config_setting_t* config_setting_set_bool_elem(config_setting_t *setting, int idx, int value)
References config_setting_get_elem, config_setting_set_bool, CONFIG_TYPE_ARRAY, CONFIG_TYPE_BOOL, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API config_setting_t* config_setting_set_string_elem(config_setting_t *setting, int idx, const char *value)
References config_setting_get_elem, config_setting_set_string, CONFIG_TYPE_ARRAY, CONFIG_TYPE_LIST, CONFIG_TYPE_STRING, NULL, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API int config_setting_index(const config_setting_t *setting)
References config_list_t::elements, config_list_t::length, config_value_t::list, config_setting_t::parent, config_setting_t::value.
LIBCONFIG_API int config_setting_length(const config_setting_t *setting)
References CONFIG_TYPE_ARRAY, CONFIG_TYPE_GROUP, CONFIG_TYPE_LIST, config_list_t::length, config_value_t::list, config_setting_t::type, config_setting_t::value.
LIBCONFIG_API config_setting_t* config_setting_get_elem(const config_setting_t *setting, unsigned int idx)
References CONFIG_TYPE_ARRAY, CONFIG_TYPE_GROUP, CONFIG_TYPE_LIST, config_list_t::elements, config_list_t::length, config_value_t::list, NULL, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_from, config_setting_get_bool_elem, config_setting_get_float_elem, config_setting_get_int64_elem, config_setting_get_int_elem, config_setting_get_string_elem, config_setting_set_bool_elem, config_setting_set_float_elem, config_setting_set_int64_elem, config_setting_set_int_elem, config_setting_set_string_elem.
LIBCONFIG_API config_setting_t* config_setting_get_member(const config_setting_t *setting, const char *name)
References CONFIG_TYPE_GROUP, config_value_t::list, NULL, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_from, config_setting_add, config_setting_lookup_bool, config_setting_lookup_float, config_setting_lookup_int, config_setting_lookup_int64, config_setting_lookup_string, libconfig::Setting::getLength.
LIBCONFIG_API config_setting_t* config_setting_add(config_setting_t *parent, const char *name, int type)
References config_setting_get_member, CONFIG_TYPE_ARRAY, CONFIG_TYPE_LIST, CONFIG_TYPE_NONE, NULL, config_setting_t::type.
Referenced by yyparse.
LIBCONFIG_API int config_setting_remove(config_setting_t *parent, const char *name)
References CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_GROUP, config_value_t::list, config_setting_t::type, config_setting_t::value.
Referenced by libconfig::Setting::remove.
LIBCONFIG_API int config_setting_remove_elem(config_setting_t *parent, unsigned int idx)
References CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_ARRAY, CONFIG_TYPE_GROUP, CONFIG_TYPE_LIST, config_list_t::length, config_value_t::list, config_setting_t::type, config_setting_t::value.
Referenced by libconfig::Setting::add.
LIBCONFIG_API void config_setting_set_hook(config_setting_t *setting, void *hook)
References config_setting_t::hook.
LIBCONFIG_API config_setting_t* config_lookup(const config_t *config, const char *path)
References config_lookup_from, config_t::root.
Referenced by config_lookup_bool, config_lookup_float, config_lookup_int, config_lookup_int64, config_lookup_string, libconfig::Config::exists.
LIBCONFIG_API config_setting_t* config_lookup_from(config_setting_t *setting, const char *path)
References config_setting_get_elem, config_setting_get_member, NULL, PATH_TOKENS.
Referenced by config_lookup.
LIBCONFIG_API int config_lookup_int(const config_t *config, const char *path, int *value)
References CONFIG_FALSE, config_lookup.
LIBCONFIG_API int config_lookup_int64(const config_t *config, const char *path, long long *value)
References CONFIG_FALSE, config_lookup.
LIBCONFIG_API int config_lookup_float(const config_t *config, const char *path, double *value)
References CONFIG_FALSE, config_lookup.
LIBCONFIG_API int config_lookup_bool(const config_t *config, const char *path, int *value)
References CONFIG_FALSE, config_lookup, config_setting_get_bool, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_BOOL.
LIBCONFIG_API int config_lookup_string(const config_t *config, const char *path, const char **value)
References CONFIG_FALSE, config_lookup, config_setting_get_string, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_STRING.