libconfig.c
PATH_TOKENS
Referenced by config_lookup_from.
CHUNK_SIZE
FLOAT_PRECISION
_new
Referenced by config_init.
_delete
Referenced by config_destroy, config_set_include_dir, config_setting_set_string.
const char* __io_error
static void __config_list_destroy(config_list_t *list)
static void __config_write_setting(const config_setting_t *setting, FILE *stream, int depth, unsigned short tab_width)
int libconfig_yyparse(void *scanner, struct parse_context *ctx, struct scan_context *scan_ctx)
int libconfig_yylex_init_extra(struct scan_context *scan_ctx, yyscan_t *scanner)
static void __config_locale_override(void)
static void __config_locale_restore(void)
static int __config_name_compare(const char *a, const char *b)
static void __config_indent(FILE *stream, int depth, unsigned short w)
static void __config_write_value(const config_value_t *value, int type, int format, int depth, unsigned short tab_width, FILE *stream)
static void __config_list_add(config_list_t *list, config_setting_t *setting)
static config_setting_t* __config_list_search(config_list_t *list, const char *name, unsigned int *idx)
static config_setting_t* __config_list_remove(config_list_t *list, int idx)
static void __config_setting_destroy(config_setting_t *setting)
static int __config_vector_checktype(const config_setting_t *vector, int type)
static int __config_validate_name(const char *name)
static int __config_read(config_t *config, FILE *stream, const char *filename, const char *str)
int config_read(config_t *config, FILE *stream)
References NULL.
int config_read_string(config_t *config, const char *str)
References NULL.
void config_write(const config_t *config, FILE *stream)
References config_t::root, config_t::tab_width.
Referenced by config_write_file.
int config_read_file(config_t *config, const char *filename)
References CONFIG_FALSE, config_t::error_text, config_t::error_type, NULL.
Referenced by libconfig::Config::writeFile.
int config_write_file(config_t *config, const char *filename)
References CONFIG_FALSE, CONFIG_TRUE, config_write, config_t::error_text, config_t::error_type.
void config_destroy(config_t *config)
References _delete, config_t::filenames, config_t::include_dir, config_t::num_filenames, config_t::root.
void config_init(config_t *config)
References _new.
Referenced by libconfig::Config::~Config.
void config_set_auto_convert(config_t *config, int flag)
References config_t::flags.
int config_get_auto_convert(const config_t *config)
References CONFIG_OPTION_AUTOCONVERT, config_t::flags.
Referenced by config_setting_set_int, config_setting_set_int64.
static config_setting_t* config_setting_create(config_setting_t *parent, const char *name, int type)
static int __config_setting_get_int(const config_setting_t *setting, int *value)
int config_setting_get_int(const config_setting_t *setting)
Referenced by config_setting_get_int_elem, libconfig::Setting::operator unsigned int.
static int __config_setting_get_int64(const config_setting_t *setting, long long *value)
long long config_setting_get_int64(const config_setting_t *setting)
Referenced by config_setting_get_int64_elem, libconfig::Setting::operator unsigned long long.
int config_setting_lookup_int(const config_setting_t *setting, const char *name, int *value)
References CONFIG_FALSE, config_setting_get_member.
int config_setting_lookup_int64(const config_setting_t *setting, const char *name, long long *value)
References CONFIG_FALSE, config_setting_get_member.
static int __config_setting_get_float(const config_setting_t *setting, double *value)
double config_setting_get_float(const config_setting_t *setting)
Referenced by config_setting_get_float_elem, libconfig::Setting::operator const char *, libconfig::Setting::operator float.
int config_setting_lookup_float(const config_setting_t *setting, const char *name, double *value)
References CONFIG_FALSE, config_setting_get_member.
int config_setting_lookup_string(const config_setting_t *setting, const char *name, const char **value)
References CONFIG_FALSE, config_setting_get_member, config_setting_get_string, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_STRING.
int config_setting_lookup_bool(const config_setting_t *setting, const char *name, int *value)
References CONFIG_FALSE, config_setting_get_bool, config_setting_get_member, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_BOOL.
int config_setting_set_int(config_setting_t *setting, int value)
References config_setting_t::config, CONFIG_FALSE, config_get_auto_convert, CONFIG_TRUE, CONFIG_TYPE_FLOAT, CONFIG_TYPE_INT, CONFIG_TYPE_NONE, config_value_t::fval, config_value_t::ival, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_int_elem, libconfig::Setting::operator=, yyparse.
int config_setting_set_int64(config_setting_t *setting, long long value)
References config_setting_t::config, CONFIG_FALSE, config_get_auto_convert, CONFIG_TRUE, CONFIG_TYPE_FLOAT, CONFIG_TYPE_INT, CONFIG_TYPE_INT64, CONFIG_TYPE_NONE, config_value_t::fval, INT32_MAX, INT32_MIN, config_value_t::ival, config_value_t::llval, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_int64_elem, libconfig::Setting::operator=, yyparse.
int config_setting_set_float(config_setting_t *setting, double value)
References config_setting_t::config, CONFIG_FALSE, CONFIG_OPTION_AUTOCONVERT, CONFIG_TRUE, CONFIG_TYPE_FLOAT, CONFIG_TYPE_INT, CONFIG_TYPE_INT64, CONFIG_TYPE_NONE, config_t::flags, config_value_t::fval, config_value_t::ival, config_value_t::llval, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_float_elem, libconfig::Setting::operator=, yyparse.
int config_setting_get_bool(const config_setting_t *setting)
References CONFIG_TYPE_BOOL, config_value_t::ival, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_bool, config_setting_lookup_bool, libconfig::Setting::operator int.
int config_setting_set_bool(config_setting_t *setting, int value)
References CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_BOOL, CONFIG_TYPE_NONE, config_value_t::ival, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_bool_elem, libconfig::Setting::operator=, yyparse.
const char* config_setting_get_string(const config_setting_t *setting)
References CONFIG_TYPE_STRING, NULL, config_value_t::sval, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_string, config_setting_lookup_string, libconfig::Setting::operator std::string.
int config_setting_set_string(config_setting_t *setting, const char *value)
References _delete, CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_NONE, CONFIG_TYPE_STRING, NULL, config_value_t::sval, config_setting_t::type, config_setting_t::value.
Referenced by config_setting_set_string_elem, libconfig::Setting::operator=, libconfig::Setting::operator[], yyparse.
int config_setting_set_format(config_setting_t *setting, short format)
References CONFIG_FALSE, CONFIG_FORMAT_DEFAULT, CONFIG_FORMAT_HEX, CONFIG_TRUE, CONFIG_TYPE_INT, CONFIG_TYPE_INT64, config_setting_t::format, config_setting_t::type.
Referenced by yyparse.
short config_setting_get_format(const config_setting_t *setting)
References config_setting_t::config, config_t::default_format, config_setting_t::format.
config_setting_t* config_lookup_from(config_setting_t *setting, const char *path)
References config_setting_get_elem, config_setting_get_member, NULL, PATH_TOKENS.
Referenced by config_lookup.
config_setting_t* config_lookup(const config_t *config, const char *path)
References config_lookup_from, config_t::root.
Referenced by config_lookup_bool, config_lookup_float, config_lookup_int, config_lookup_int64, config_lookup_string, libconfig::Config::exists.
int config_lookup_string(const config_t *config, const char *path, const char **value)
References CONFIG_FALSE, config_lookup, config_setting_get_string, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_STRING.
int config_lookup_int(const config_t *config, const char *path, int *value)
References CONFIG_FALSE, config_lookup.
int config_lookup_int64(const config_t *config, const char *path, long long *value)
References CONFIG_FALSE, config_lookup.
int config_lookup_float(const config_t *config, const char *path, double *value)
References CONFIG_FALSE, config_lookup.
int config_lookup_bool(const config_t *config, const char *path, int *value)
References CONFIG_FALSE, config_lookup, config_setting_get_bool, config_setting_type, CONFIG_TRUE, CONFIG_TYPE_BOOL.
int config_setting_get_int_elem(const config_setting_t *vector, int idx)
References config_setting_get_elem, config_setting_get_int.
config_setting_t* config_setting_set_int_elem(config_setting_t *vector, int idx, int value)
References config_setting_get_elem, config_setting_set_int, CONFIG_TYPE_ARRAY, CONFIG_TYPE_INT, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
long long config_setting_get_int64_elem(const config_setting_t *vector, int idx)
References config_setting_get_elem, config_setting_get_int64.
config_setting_t* config_setting_set_int64_elem(config_setting_t *vector, int idx, long long value)
References config_setting_get_elem, config_setting_set_int64, CONFIG_TYPE_ARRAY, CONFIG_TYPE_INT64, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
double config_setting_get_float_elem(const config_setting_t *vector, int idx)
References config_setting_get_elem, config_setting_get_float.
config_setting_t* config_setting_set_float_elem(config_setting_t *vector, int idx, double value)
References config_setting_get_elem, config_setting_set_float, CONFIG_TYPE_ARRAY, CONFIG_TYPE_FLOAT, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
int config_setting_get_bool_elem(const config_setting_t *vector, int idx)
References CONFIG_FALSE, config_setting_get_elem, CONFIG_TYPE_BOOL, config_value_t::ival, config_setting_t::type, config_setting_t::value.
config_setting_t* config_setting_set_bool_elem(config_setting_t *vector, int idx, int value)
References config_setting_get_elem, config_setting_set_bool, CONFIG_TYPE_ARRAY, CONFIG_TYPE_BOOL, CONFIG_TYPE_LIST, NULL, config_setting_t::type.
Referenced by yyparse.
const char* config_setting_get_string_elem(const config_setting_t *vector, int idx)
References config_setting_get_elem, CONFIG_TYPE_STRING, NULL, config_value_t::sval, config_setting_t::type, config_setting_t::value.
config_setting_t* config_setting_set_string_elem(config_setting_t *vector, int idx, const char *value)
References config_setting_get_elem, config_setting_set_string, CONFIG_TYPE_ARRAY, CONFIG_TYPE_LIST, CONFIG_TYPE_STRING, NULL, config_setting_t::type.
Referenced by yyparse.
config_setting_t* config_setting_get_elem(const config_setting_t *vector, unsigned int idx)
References CONFIG_TYPE_ARRAY, CONFIG_TYPE_GROUP, CONFIG_TYPE_LIST, config_list_t::elements, config_list_t::length, config_value_t::list, NULL, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_from, config_setting_get_bool_elem, config_setting_get_float_elem, config_setting_get_int64_elem, config_setting_get_int_elem, config_setting_get_string_elem, config_setting_set_bool_elem, config_setting_set_float_elem, config_setting_set_int64_elem, config_setting_set_int_elem, config_setting_set_string_elem.
config_setting_t* config_setting_get_member(const config_setting_t *setting, const char *name)
References CONFIG_TYPE_GROUP, config_value_t::list, NULL, config_setting_t::type, config_setting_t::value.
Referenced by config_lookup_from, config_setting_add, config_setting_lookup_bool, config_setting_lookup_float, config_setting_lookup_int, config_setting_lookup_int64, config_setting_lookup_string, libconfig::Setting::getLength.
void config_set_destructor(config_t *config, void(*destructor)(void *))
References config_t::destructor.
Referenced by libconfig::Config::~Config.
void config_set_include_dir(config_t *config, const char *include_dir)
References _delete, config_t::include_dir.
int config_setting_length(const config_setting_t *setting)
References CONFIG_TYPE_ARRAY, CONFIG_TYPE_GROUP, CONFIG_TYPE_LIST, config_list_t::length, config_value_t::list, config_setting_t::type, config_setting_t::value.
void config_setting_set_hook(config_setting_t *setting, void *hook)
References config_setting_t::hook.
config_setting_t* config_setting_add(config_setting_t *parent, const char *name, int type)
References config_setting_get_member, CONFIG_TYPE_ARRAY, CONFIG_TYPE_LIST, CONFIG_TYPE_NONE, NULL, config_setting_t::type.
Referenced by yyparse.
int config_setting_remove(config_setting_t *parent, const char *name)
References CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_GROUP, config_value_t::list, config_setting_t::type, config_setting_t::value.
Referenced by libconfig::Setting::remove.
int config_setting_remove_elem(config_setting_t *parent, unsigned int idx)
References CONFIG_FALSE, CONFIG_TRUE, CONFIG_TYPE_ARRAY, CONFIG_TYPE_GROUP, CONFIG_TYPE_LIST, config_list_t::length, config_value_t::list, config_setting_t::type, config_setting_t::value.
Referenced by libconfig::Setting::add.
int config_setting_index(const config_setting_t *setting)
References config_list_t::elements, config_list_t::length, config_value_t::list, config_setting_t::parent, config_setting_t::value.