tld
const int tld::TLD_WINDOW_SIZE
const int tld::TLD_WINDOW_OFFSET_SIZE
char tld::help_text[][]
int tld::opterr
int tld::optind
Referenced by tld::Config::init.
int tld::optopt
char * tld::optarg
Referenced by tld::Config::init.
string tld::window_name
CvFont tld::font
IplImage* tld::img0
IplImage* tld::img1
CvPoint tld::point
CvRect* tld::bb
int tld::drag
void tld::tldNormalizeImg(const Mat &img, float *output)
Referenced by tldExtractNormalizedPatch.
CvRect tld::tldBoundaryToRect(int *boundary)
Referenced by tldExtractSubImage.
void tld::tldExtractSubImage(const Mat &img, Mat &subImage, CvRect rect)
Referenced by tldExtractNormalizedPatch, tldExtractSubImage.
void tld::tldExtractSubImage(const Mat &img, Mat &subImage, int *boundary)
References tldBoundaryToRect, tldExtractSubImage.
void tld::tldExtractNormalizedPatch(const Mat &img, int x, int y, int w, int h, float *output)
References tldExtractSubImage, tldNormalizeImg.
Referenced by tldExtractNormalizedPatchBB, tldExtractNormalizedPatchRect.
void tld::tldExtractNormalizedPatchBB(const Mat &img, int *boundary, float *output)
References tldExtractDimsFromArray, tldExtractNormalizedPatch.
void tld::tldExtractNormalizedPatchRect(const Mat &img, Rect *rect, float *output)
References tldExtractNormalizedPatch.
float tld::CalculateMean(float *value, int n)
float tld::tldCalcVariance(float *value, int n)
float tld::tldBBOverlap(int *bb1, int *bb2)
Referenced by tldOverlapOne, tldOverlapRectRect.
void tld::tldOverlapOne(int *windows, int numWindows, int index, vector< int > *indices, float *overlap)
References tldBBOverlap.
float tld::tldOverlapRectRect(Rect r1, Rect r2)
References tldBBOverlap.
Rect* tld::tldCopyRect(Rect *r)
void tld::tldOverlapRect(int *windows, int numWindows, Rect *boundary, float *overlap)
References tldOverlap.
void tld::tldOverlap(int *windows, int numWindows, int *boundary, float *overlap)
Referenced by tldOverlapRect.
bool tld::tldSortByOverlapDesc(pair< int, float > bb1, pair< int, float > bb2)
int tld::tldIsInside(int *bb1, int *bb2)
void tld::tldConvertBB(T1 *src, T2 *dest)
void tld::tldCopyBB(T *src, T *dest)
void tld::tldCopyBoundaryToArray(T x, T y, T width, T height, T *array)
void tld::tldExtractDimsFromArray(T *boundary, T *x, T *y, T *width, T *height)
Referenced by tldExtractNormalizedPatchBB.
void tld::tldRectToArray(cv::Rect rect, T *boundary)
cv::Rect tld::tldArrayToRect(T *boundary)
Referenced by Main::doWork.
void tld::tldNormalizeImg(const cv::Mat &img, float *result, int size)
void tld::tldExtractNormalizedPatch(const cv::Mat &img, int x, int y, int w, int h, float *output)
void tld::tldExtractNormalizedPatchBB(const cv::Mat &img, int *boundary, float *output)
void tld::tldExtractNormalizedPatchRect(const cv::Mat &img, cv::Rect *rect, float *output)
void tld::tldExtractSubImage(const cv::Mat &img, cv::Mat &subImage, int *boundary)
void tld::tldExtractSubImage(const cv::Mat &img, cv::Mat &subImage, int x, int y, int w, int h)
float tld::tldCalcMean(float *value, int n)
bool tld::tldSortByOverlapDesc(std::pair< int, float > bb1, std::pair< int, float > bb2)
cv::Rect* tld::tldCopyRect(cv::Rect *r)
float tld::tldOverlapRectRect(cv::Rect r1, cv::Rect r2)
void tld::tldOverlapOne(int *windows, int numWindows, int index, std::vector< int > *indices, float *overlap)
void tld::tldOverlapRect(int *windows, int numWindows, cv::Rect *boundary, float *overlap)
int tld::getopt(int argc, char **argv, char *opts)
Referenced by tld::Config::init.
static void tld::mouseHandler(int event, int x, int y, int flags, void *param)
int tld::getBBFromUser(IplImage *img, CvRect &rect, Gui *gui)
Get a bounding box from the user. img image to display rect CvRect containing the coordinates of the bounding box gui initialized gui PROGRAM_EXIT if 'q' or 'Q' pressed, SUCCESS if everything went right
Referenced by Main::doWork.