scanner.c
YY_INT_ALIGNED
FLEX_SCANNER
YY_FLEX_MAJOR_VERSION
YY_FLEX_MINOR_VERSION
YY_FLEX_SUBMINOR_VERSION
FLEXINT_H
INT8_MIN
INT16_MIN
INT32_MIN
Referenced by config_setting_set_int64.
INT8_MAX
INT16_MAX
INT32_MAX
Referenced by config_setting_set_int64.
UINT8_MAX
UINT16_MAX
UINT32_MAX
yyconst
YY_NULL
YY_SC_TO_UI
YY_TYPEDEF_YY_SCANNER_T
yyin
Referenced by libconfig_yyset_in.
yyout
Referenced by libconfig_yyset_out.
yyextra
Referenced by libconfig_yyset_extra.
yyleng
yytext
yylineno
Referenced by libconfig_yyset_lineno.
yycolumn
Referenced by libconfig_yyset_column.
yy_flex_debug
Referenced by libconfig_yyset_debug.
BEGIN
YY_START
YYSTATE
YY_STATE_EOF
YY_NEW_FILE
YY_END_OF_BUFFER_CHAR
Referenced by libconfig_yy_scan_buffer.
YY_BUF_SIZE
YY_STATE_BUF_SIZE
YY_TYPEDEF_YY_BUFFER_STATE
EOB_ACT_CONTINUE_SCAN
EOB_ACT_END_OF_FILE
EOB_ACT_LAST_MATCH
YY_LESS_LINENO
yyless
unput
YY_TYPEDEF_YY_SIZE_T
YY_STRUCT_YY_BUFFER_STATE
YY_BUFFER_NEW
YY_BUFFER_NORMAL
YY_BUFFER_EOF_PENDING
YY_CURRENT_BUFFER
Referenced by libconfig_yy_flush_buffer, libconfig_yyget_column, libconfig_yyget_lineno, libconfig_yylex_destroy, libconfig_yypop_buffer_state, libconfig_yypush_buffer_state, libconfig_yyset_column, libconfig_yyset_lineno.
YY_CURRENT_BUFFER_LVALUE
Referenced by libconfig_yylex_destroy, libconfig_yypop_buffer_state, libconfig_yypush_buffer_state.
YY_FLUSH_BUFFER
yy_new_buffer
yy_set_interactive
yy_set_bol
YY_AT_BOL
libconfig_yywrap
YY_SKIP_YYWRAP
yytext_ptr
YY_DO_BEFORE_ACTION
YY_NUM_RULES
YY_END_OF_BUFFER
REJECT
yymore
YY_MORE_ADJ
YY_RESTORE_YY_MORE_OFFSET
YY_NO_UNISTD_H
YY_NO_INPUT
INITIAL
COMMENT
STRING
INCLUDE
YY_EXTRA_TYPE
yylval
Referenced by libconfig_yyset_lval.
YY_READ_BUF_SIZE
ECHO
YY_INPUT
yyterminate
YY_START_STACK_INCR
YY_FATAL_ERROR
Referenced by libconfig_yy_scan_buffer, libconfig_yy_scan_bytes.
YY_DECL_IS_OURS
YY_DECL
YY_USER_ACTION
YY_BREAK
YY_RULE_SETUP
YY_EXIT_FAILURE
yyless
YYTABLES_NAME
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void* yyscan_t
typedef struct yy_buffer_state* YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
yyconst flex_int16_t yy_accept[103][103]
yyconst flex_int32_t yy_ec[256][256]
yyconst flex_int32_t yy_meta[49][49]
yyconst flex_int16_t yy_base[113][113]
yyconst flex_int16_t yy_def[113][113]
yyconst flex_int16_t yy_nxt[253][253]
yyconst flex_int16_t yy_chk[253][253]
yyconst flex_int32_t yy_rule_can_match_eol[42][42]
void libconfig_yyrestart(FILE *input_file, yyscan_t yyscanner)
void libconfig_yy_switch_to_buffer(YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Referenced by libconfig_yy_scan_buffer.
YY_BUFFER_STATE libconfig_yy_create_buffer(FILE *file, int size, yyscan_t yyscanner)
void libconfig_yy_delete_buffer(YY_BUFFER_STATE b, yyscan_t yyscanner)
Referenced by libconfig_yylex_destroy, libconfig_yypop_buffer_state.
void libconfig_yy_flush_buffer(YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters. On the next scan, YY_INPUT will be called. b the buffer state to be flushed, usually YY_CURRENT_BUFFER. yyscanner The scanner object.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, yy_buffer_state::yy_n_chars.
void libconfig_yypush_buffer_state(YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack. The new state becomes the current state. This function will allocate the stack if necessary. new_buffer The new state. yyscanner The scanner object.
References NULL, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars.
void libconfig_yypop_buffer_state(yyscan_t yyscanner)
Removes and deletes the top of the stack, if present. The next element becomes the new top. yyscanner The scanner object.
References libconfig_yy_delete_buffer, yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by libconfig_yylex_destroy.
static void libconfig_yyensure_buffer_stack(yyscan_t yyscanner)
static void libconfig_yy_load_buffer_state(yyscan_t yyscanner)
static void libconfig_yy_init_buffer(YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
The main scanner function which does all the work.
YY_BUFFER_STATE libconfig_yy_scan_buffer(char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer. base the character buffer size the size in bytes of the character buffer yyscanner The scanner object. the newly allocated buffer state object.
References libconfig_yy_switch_to_buffer, libconfig_yyalloc, yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars.
Referenced by libconfig_yy_scan_bytes.
YY_BUFFER_STATE libconfig_yy_scan_string(yyconst char *yy_str, yyscan_t yyscanner)
Setup the input buffer state to scan a string. The next call to libconfig_yylex() will scan from a copy of str. yystr a NUL-terminated string to scan yyscanner The scanner object. the newly allocated buffer state object. If you want to scan bytes that may contain NUL values, then use libconfig_yy_scan_bytes() instead.
References libconfig_yy_scan_bytes.
YY_BUFFER_STATE libconfig_yy_scan_bytes(yyconst char *bytes, int len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes. The next call to libconfig_yylex() will scan from a copy of bytes. yybytes the byte buffer to scan _yybytes_len the number of bytes in the buffer pointed to by bytes. yyscanner The scanner object. the newly allocated buffer state object.
References libconfig_yy_scan_buffer, libconfig_yyalloc, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer.
Referenced by libconfig_yy_scan_string.
void * libconfig_yyalloc(yy_size_t, yyscan_t yyscanner)
Referenced by libconfig_yy_scan_buffer, libconfig_yy_scan_bytes, libconfig_yylex_init, libconfig_yylex_init_extra.
void * libconfig_yyrealloc(void *, yy_size_t, yyscan_t yyscanner)
void libconfig_yyfree(void *, yyscan_t yyscanner)
Referenced by libconfig_yylex_destroy.
static yy_state_type yy_get_previous_state(yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans(yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer(yyscan_t yyscanner)
static void yy_fatal_error(yyconst char msg[], yyscan_t yyscanner)
static unsigned long long fromhex(const char *s)
static int yy_init_globals(yyscan_t yyscanner)
int libconfig_yylex_init(yyscan_t *scanner)
References libconfig_yyalloc, NULL.
int libconfig_yylex_init_extra(YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
References libconfig_yyalloc, libconfig_yyset_extra, NULL.
int libconfig_yylex_destroy(yyscan_t yyscanner)
References libconfig_yy_delete_buffer, libconfig_yyfree, libconfig_yypop_buffer_state, yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_start_stack.
int libconfig_yyget_debug(yyscan_t yyscanner)
void libconfig_yyset_debug(int debug_flag, yyscan_t yyscanner)
References yy_flex_debug.
YY_EXTRA_TYPE libconfig_yyget_extra(yyscan_t yyscanner)
Get the user-defined data for this scanner. yyscanner The scanner object.
void libconfig_yyset_extra(YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data. This data is never touched by the scanner. user_defined The data to be associated with this scanner. yyscanner The scanner object.
References yyextra.
Referenced by libconfig_yylex_init_extra.
FILE * libconfig_yyget_in(yyscan_t yyscanner)
Get the input stream. yyscanner The scanner object.
void libconfig_yyset_in(FILE *in_str, yyscan_t yyscanner)
Set the input stream. This does not discard the current input buffer. in_str A readable stream. yyscanner The scanner object. libconfig_yy_switch_to_buffer
References yyin.
FILE * libconfig_yyget_out(yyscan_t yyscanner)
Get the output stream. yyscanner The scanner object.
void libconfig_yyset_out(FILE *out_str, yyscan_t yyscanner)
References yyout.
int libconfig_yyget_leng(yyscan_t yyscanner)
Get the length of the current token. yyscanner The scanner object.
char * libconfig_yyget_text(yyscan_t yyscanner)
Get the current token. yyscanner The scanner object.
int libconfig_yyget_lineno(yyscan_t yyscanner)
Get the current line number. yyscanner The scanner object.
References YY_CURRENT_BUFFER.
void libconfig_yyset_lineno(int line_number, yyscan_t yyscanner)
Set the current line number. line_number yyscanner The scanner object.
References YY_CURRENT_BUFFER, yylineno.
YYSTYPE * libconfig_yyget_lval(yyscan_t yyscanner)
void libconfig_yyset_lval(YYSTYPE *yylval_param, yyscan_t yyscanner)
References yylval.
int libconfig_yywrap(yyscan_t yyscanner)
static void yy_flex_strncpy(char *, yyconst char *, int, yyscan_t yyscanner)
int libconfig_yylex(YYSTYPE *yylval_param, yyscan_t yyscanner)
static void yy_fatal_error(yyconst char *msg, yyscan_t yyscanner)
int libconfig_yyget_column(yyscan_t yyscanner)
Get the current column number. yyscanner The scanner object.
References YY_CURRENT_BUFFER.
void libconfig_yyset_column(int column_no, yyscan_t yyscanner)
Set the current column. line_number yyscanner The scanner object.
References YY_CURRENT_BUFFER, yycolumn.